### ISSUE TITLE
Create Toast module for validation errors

### ISSUE THREAD

**Issue by wajahatkarim3** [wajahatkarim3/EasyValidation#18]
Create `Toast` module for EasyValidation. This module will display validation errors from Failure Callback in Toasts.

**Comment by wajahatkarim3** [comment]
Well, the basic idea is to add a feature in Easy Validation library through which every time validation check fails, the ```Toast``` will be shown with the error message displayed. 
At this moment, the library gives an error in the error callback and developers manually have to show Toast or any kind of error they want from that callback.
The purpose of this issue to provide a module which allows developers to show Toast without any additional code on their side. 
The idea way to do is to override the callback and show the Toast in it.

**Comment by wajahatkarim3** [comment]
Thank you @chikka for your interest. Yes, you can do this. For you I have added another commit 737b53c to add some initial setups. I have added an `EditTextKtx.kt` class in `Toast` module with two `nonEmptyToast()` methods. You will have to copy all the methods from `core.view_ktx` package and add methods as I have done it. 
Do let me know if you wants to do this (I know this is late. I was out of town) and if you have any more questions, let me know 😄

**Comment by chikka** [comment]
@wajahatkarim3 I wan to do it :). Only one question is why we are using [callback](https://github.com/wajahatkarim3/EasyValidation/blob/737b53c0c249d581a1f3ad0d7a559186076f5a54/easyvalidation-toasts/src/main/java/com/wajahatkarim3/easyvalidation/toasts/view_ktx/EditTextKtx.kt#L15) with message argument  as we are already having errorMsg as second argument. or is there any other purpose?

**Comment by wajahatkarim3** [comment]
Actually, the library has default messages for each validation. But, if the user wants to set a custom message, then that message will be passed in the callback. And if there's no custom message, then the callback will get the default message.

**Comment by chikka** [comment]
@wajahatkarim3 ok. will start working on it and will send PR once it is completed.Thanks!

**Comment by wajahatkarim3** [comment]
Fixed in the pull request #33 by @chikka . Thank you again 😄
