### ISSUE TITLE
Add custom error message in all rule methods in Validator class

### ISSUE THREAD

**Issue by wajahatkarim3** [wajahatkarim3/EasyValidation#24]
Every `Rule` class such as [`NonEmptyRule`](https://github.com/wajahatkarim3/EasyValidation/blob/master/easyvalidation-core/src/main/java/com/wajahatkarim3/easyvalidation/core/rules/NonEmptyRule.kt) has a variable `errorMsg` in the constructor with a pre-defined value which is returned as the error message when validation is failed. 

For example, in [`NonEmptyRule`](https://github.com/wajahatkarim3/EasyValidation/blob/master/easyvalidation-core/src/main/java/com/wajahatkarim3/easyvalidation/core/rules/NonEmptyRule.kt)
```kotlin
class NonEmptyRule(var errorMsg: String = "Can't be empty!") : BaseRule
```

Also, in [`Validator`](https://github.com/wajahatkarim3/EasyValidation/blob/master/easyvalidation-core/src/main/java/com/wajahatkarim3/easyvalidation/core/Validator.kt) class, each rule has a method for quick validation like this for `NonEmptyRule`:

```kotlin
fun nonEmpty() : Validator
{
    addRule(NonEmptyRule())
    return this
}
```

**Task**
The goal of this task is to add error messages in all the rule methods of `Validator` class like this:
```kotlin
fun nonEmpty(errorMsg: String = "Can't be empty!") : Validator
{
    addRule(NonEmptyRule(errorMsg))
    return this
}
```
Please note that there's an `errorMsg` variable has been passed in the rule method now with a pre-defined value. This value should be copied from the passed rule (here `NonEmptyRule`).

**Comment by renanrbs** [comment]
hey @wajahatkarim3, the messages shoud be duplicated on the validator class? isnt this going to make things harder if the message needs to be changed? Especially because the project is not internationalized yet

**Comment by wajahatkarim3** [comment]
That's really good point. I didn't think about it. Well the purpose is to add functionality which can allow developers to customize message. How about we overload each rule method in `Validator` class like this:

```kotlin
fun nonEmpty(errorMsg: String) : Validator
{
 addRule(NonEmptyRule(errorMsg)) 
return this
}
```
