### ISSUE TITLE
 Add custom error message in all rules for view extension methods

### ISSUE THREAD

**Issue by wajahatkarim3** [wajahatkarim3/EasyValidation#26]
In the [`view_ktx`](https://github.com/wajahatkarim3/EasyValidation/tree/master/easyvalidation-core/src/main/java/com/wajahatkarim3/easyvalidation/core/view_ktx) package, there are few classes for view extensions such as `EditTextKtx.kt`, `TextViewKtx.kt` etc. These classes contains kotlin extension methods of validation rules for respective `View`s. 

For example, [`EditTextKtx.kt`](https://github.com/wajahatkarim3/EasyValidation/blob/master/easyvalidation-core/src/main/java/com/wajahatkarim3/easyvalidation/core/view_ktx/EditTextKtx.kt) for `NonEmptyRule` check, we have two methods (one normal, and other with callback) like:
```kotlin
fun EditText.nonEmpty() : Boolean
{
    return validator().nonEmpty().check()
}

fun EditText.nonEmpty(callback: (message: String) -> Unit) : Boolean
{
    return validator().nonEmpty()
            .addErrorCallback {
                callback.invoke(it)
            }
            .check()
}
```

**Task**
The goal of this task is to add a `Nullable` parameter with name `errorMsg` in each of these methods and pass it in the validation check in the method definition like this:
```kotlin
fun EditText.nonEmpty(errorMsg:String? = null) : Boolean
{
    return validator().nonEmpty(errorMsg).check()
}

fun EditText.nonEmpty(callback: (message: String) -> Unit, errorMsg:String? = null) : Boolean
{
    return validator().nonEmpty(errorMsg)
            .addErrorCallback {
                callback.invoke(it)
            }
            .check()
}
```
Please note that how I have passed the `errorMsg` paramter in the checks of `validator()` inside the method definitions.

This should be done for all methods of 5 classes inside `view_ktx` package:
* [`EditTextKtx.kt`](https://github.com/wajahatkarim3/EasyValidation/blob/master/easyvalidation-core/src/main/java/com/wajahatkarim3/easyvalidation/core/view_ktx/EditTextKtx.kt)
* [`TextViewKtx.kt`](https://github.com/wajahatkarim3/EasyValidation/blob/master/easyvalidation-core/src/main/java/com/wajahatkarim3/easyvalidation/core/view_ktx/TextViewKtx.kt)
* [`SpinnerKtx.kt`](https://github.com/wajahatkarim3/EasyValidation/blob/master/easyvalidation-core/src/main/java/com/wajahatkarim3/easyvalidation/core/view_ktx/SpinnerKtx.kt)
* [`StringKtx.kt`](https://github.com/wajahatkarim3/EasyValidation/blob/master/easyvalidation-core/src/main/java/com/wajahatkarim3/easyvalidation/core/view_ktx/StringKtx.kt)
* [`AutoCompleteTextViewKtx.kt`](https://github.com/wajahatkarim3/EasyValidation/blob/master/easyvalidation-core/src/main/java/com/wajahatkarim3/easyvalidation/core/view_ktx/AutoCompleteTextViewKtx.kt)

**Comment by emaiax** [comment]
Also, I would like to have all validations checked at once instead of checking if all fields are validated one by one, since the validate method returns whether the first check returns false.

What a `failFast: Boolean = true` option? It makes sense @wajahatkarim3? I'd be happy to contribute for that.

**Comment by wajahatkarim3** [comment]
Thanks @emaiax for the great suggestion. Yes I would love your contributions. :smile:

**Comment by wajahatkarim3** [comment]
Oh I am so sorry @emaiax for the trouble you had with setting up the library. Well, I haven't tried it on IntelliJ but I think I should delete the `.idea | .gradle` directories from the Github repo. 

Thank you for letting me know 👍

**Comment by emaiax** [comment]
Yeah, it didn't work either. I'm having a few issues with `anottation-support` versions.. had to comment code and then, no specs were being found to be run.

I'll try this out on Android Studio.

**Comment by emaiax** [comment]
Hi @wajahatkarim3. I've installed Android Studio, build the project from scratch and BOOM. Same issue. I'll move the conversation to #29. tks!

**Comment by wajahatkarim3** [comment]
Hello @emaiax 
Thank you for taking time to fix these issues. I just found the problem. It was caused after the merging of pull request #27 and some of my own code commits. I am fixing this and adding few new commits on ```master``` branch. I will let you know real quick once its done. 👍

**Comment by wajahatkarim3** [comment]
@emaiax  I have fixed the compile errors and also finished this issue. So, I am closing this issue and also issue #29 as that was also part of this issue.
