### ISSUE TITLE
Trim EditText string in nonEmpty() 

### ISSUE THREAD

**Issue by therajanmaurya** [wajahatkarim3/EasyValidation#48]
nonEmpty() does not checks if EditText contains only spaces or not. If EditText contains only spaces It should validate EditText as Empty.

@wajahatkarim3 how does it sound. If solution is already present, can you please guide me?

**Comment by therajanmaurya** [comment]
I thought about this and I came to the decision that It should not be in the library because Kotlin gives us a great kotlin extension 

```
fun EditText.trim(): EditText {
    return this.apply { setText(this.text.trim()) }
}
```

Something like this would solve the problem and I think that the library has nothing to do handle this situation.

**Comment by wajahatkarim3** [comment]
Thank you for your solution. I think maybe we can add another trimmed empty rule for this for users if they want it.

**Comment by therajanmaurya** [comment]
> Thank you for your solution. I think maybe we can add another trimmed empty rule for this for users if they want it.

yes it can be a good idea too to add trim() method after calling validator() like this 

```
EditText.validator().trim().nonEmpty()....
````
